name: API Publish Docker Images

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "api/**"

jobs:
    build-FLAGSMITHAPI-image:
        runs-on: ubuntu-latest
        name: Flagsmith API Publish Docker Image
        steps:        
              - name: download code
                uses: actions/checkout@v1
              
              - name: Build and Push Image to ECR
                env: 
                   tag: test
                   dd_service: flagsmith
                   dd_env: test
                run: |
                  docker login ${{ secrets.FLAGSMITHAPI_ECR_REPOSITORY_URL }} -u=${{ secrets.FLAGSMITHAPI_ECR_USERNAME }} -p=${{ secrets.FLAGSMITHAPI_ECR_PASSWORD }}
                  docker build --build-arg DD_SERVICE=$DD_SERVICE --build-arg DD_ENV=$DD_ENV --target base -t ${{ secrets.PRODUCTION_ECR_REPOSITORY_URL }}:$tag .
                  docker push ${{ secrets.FLAGSMITHAPI_ECR_REPOSITORY_URL }} --all-tags